remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: python-llms-wrapper
description: A library for making it simple and straightforward to use many different LLMs, including tooling

show_downloads: false
